// Generated by CoffeeScript 1.3.3
(function() {
  var app, config, exports, express, http, mongoStore, mongoose, path, routes;

  path = require("path");

  config = require("./config");

  express = require("express");

  routes = require("./server/routes");

  http = require("http");

  mongoStore = require("connect-mongodb");

  mongoose = require("mongoose");

  app = express();

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.set("views", path.join(__dirname, "views"));
    app.set("view engine", "jade");
    app.set("basepath", "/");
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, "public")));
    return app.use(express["static"](path.join(__dirname, "docs")));
  });

  app.configure("development", function() {
    app.set("port", process.env.PORT || 3000);
    app.set("db-uri", process.env.MONGOLAB_URI || process.env.MONGODB_URI || config.default_db_uri);
    app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
    return app.set("view options", {
      layout: false,
      pretty: true
    });
  });

  app.configure("test", function() {
    app.set("port", process.env.PORT || 3001);
    app.set("db-uri", process.env.MONGOLAB_URI || process.env.MONGODB_URI || config.default_db_uri);
    return app.set("view options", {
      layout: false,
      pretty: true
    });
  });

  app.configure("production", function() {
    app.set("port", process.env.PORT || 80);
    app.set("db-uri", process.env.MONGOLAB_URI || process.env.MONGODB_URI || config.default_db_uri);
    app.set("view options", {
      layout: false
    });
    return app.use(express.errorHandler());
  });

  mongoose.connect(app.get("db-uri"));

  exports = module.exports = mongoose;

  app.get("/doc", function(req, res) {
    return res.render("doc/index");
  });

  app.get("/", routes.index);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
