// Generated by CoffeeScript 1.3.3
(function() {
  var User, app, mongoose, request_helper, user;

  app = require("../../app");

  mongoose = require("mongoose");

  User = require("../../server/models/user");

  request_helper = require("./request_helper");

  mongoose.connection.collection("users").drop();

  user = new User({
    name: "test_user",
    email: "blah"
  });

  user.setPassword("test");

  user.save(function(err, result) {
    if (err) {
      throw err;
    }
  });

  exports.post_login = function(done) {
    return request_helper.post("/login", {
      username: user.name,
      password: "test"
    }, (function(err, result, done) {
      if (err) {
        throw err;
      }
      return done();
    }), done);
  };

}).call(this);
