// Generated by CoffeeScript 1.3.3
(function() {
  var getUrlFor, request, sendRequest;

  getUrlFor = function(route) {
    return "http://localhost:3000" + route;
  };

  sendRequest = function(method, route, body, callback, done) {
    return request[method]({
      url: getUrlFor(route),
      json: body
    }, function(err, res, b) {
      return callback(err, res, done);
    });
  };

  request = require("request");

  module.exports = {
    post: function(route, body, callback, done) {
      return sendRequest("post", route, body, callback, done);
    },
    get: function(route, callback, done) {
      return sendRequest("get", route, null, callback, done);
    }
  };

}).call(this);
