// Generated by CoffeeScript 1.3.3
(function() {
  var Customer;

  Customer = require("../models/customer");

  module.exports = function(app, restrict) {
    app.get("/customer/create", restrict, function(req, res) {
      return res.render("customer/create");
    });
    return app.get("/customer/list", restrict, function(req, res, next) {
      var customers;
      return customers = Customer.find({}, ["name"], function(err, docs) {
        if (err) {
          return next(err);
        }
        return res.render("customer/list", {
          customers: docs
        });
      });
    });
  };

}).call(this);
